# Generated by Django 4.2.6 on 2023-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_phone_numer_investoruser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoruser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/investors_logos'),
        ),
        migrations.AddField(
            model_name='investoruser',
            name='company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
