# Generated by Django 4.2.6 on 2023-11-15 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_investoruser_company_logo_investoruser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoruser',
            name='webpage',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator(code='Invalid web address', regex='^https:\\/\\/[www]?.+\\..+$')]),
            preserve_default=False,
        ),
    ]
