# Generated by Django 4.2.6 on 2023-10-09 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_investoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_numer', models.CharField(max_length=10)),
                ('apartment_numer', models.CharField(max_length=10, null=True)),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0, message='Value must be greater than 10 square meters'), django.core.validators.MaxValueValidator(300.0, message='Value cannot be greater than 300 square meters')])),
                ('rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Value must be greater or exual 1'), django.core.validators.MaxValueValidator(10, message='Value cannot be greater than 10')])),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/investments')),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.investoruser')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/apartments')),
                ('caption', models.CharField(max_length=60)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Investments.apartment')),
            ],
        ),
    ]
