# Generated by Django 4.2.6 on 2023-10-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='apartment_numer',
            new_name='apartment_number',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='building_numer',
            new_name='building_number',
        ),
    ]
