# Generated by Django 4.2.6 on 2023-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0006_remove_investment_resized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='caption',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
