# Generated by Django 4.2.6 on 2023-10-24 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0008_apartmentsearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearchresult',
            name='max_rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Value must be a positive integer'), django.core.validators.MaxValueValidator(10, 'Value cannot exceed 10')]),
            preserve_default=False,
        ),
    ]
