# Generated by Django 4.2.6 on 2023-10-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0010_rename_gas_ac_apartmentsearchresult_has_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearchresult',
            name='has_basement',
            field=models.BooleanField(null=True),
        ),
    ]
