# Generated by Django 4.2.6 on 2023-11-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0011_apartmentsearchresult_has_basement'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
