# Generated by Django 4.2.6 on 2023-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_message_description_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
