# Generated by Django 4.2.6 on 2023-11-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_alter_message_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLinkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('link_text', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Messages.messagelinkattachment'),
        ),
    ]
